/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CropYield {
  'id' : bigint,
  'yieldKg' : number,
  'userId' : Principal,
  'year' : bigint,
  'cropName' : string,
  'estateId' : bigint,
}
export interface DailyLog {
  'id' : bigint,
  'userId' : Principal,
  'date' : string,
  'pesticideMl' : number,
  'laborHours' : number,
  'fertilizerKg' : number,
  'estateId' : bigint,
  'rainfallMM' : number,
}
export interface Estate {
  'id' : bigint,
  'estateCare' : string,
  'userId' : Principal,
  'areaAcres' : number,
  'name' : string,
  'createdAt' : bigint,
  'location' : string,
}
export interface Forecast {
  'id' : bigint,
  'userId' : Principal,
  'cropName' : string,
  'forecastDate' : string,
  'forecastNote' : string,
  'estateId' : bigint,
}
export interface LabourEntry {
  'id' : bigint,
  'workType' : string,
  'wagePerDay' : number,
  'userId' : Principal,
  'date' : string,
  'numberOfDays' : bigint,
  'totalAmount' : number,
  'estateId' : bigint,
  'workerName' : string,
}
export interface RainfallLog {
  'id' : bigint,
  'userId' : Principal,
  'date' : string,
  'notes' : string,
  'estateId' : bigint,
  'rainfallMM' : number,
}
export interface RevenueEntry {
  'id' : bigint,
  'userId' : Principal,
  'date' : string,
  'description' : string,
  'estateId' : bigint,
  'amount' : number,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'adminDeleteCropYield' : ActorMethod<[bigint], undefined>,
  'adminDeleteDailyLog' : ActorMethod<[bigint], undefined>,
  'adminDeleteEstate' : ActorMethod<[bigint], undefined>,
  'adminDeleteLabourEntry' : ActorMethod<[bigint], undefined>,
  'adminDeleteRainfallLog' : ActorMethod<[bigint], undefined>,
  'adminDeleteRevenueEntry' : ActorMethod<[bigint], undefined>,
  'adminGetAllCropYields' : ActorMethod<[], Array<CropYield>>,
  'adminGetAllDailyLogs' : ActorMethod<[], Array<DailyLog>>,
  'adminGetAllEstates' : ActorMethod<[], Array<Estate>>,
  'adminGetAllLabourEntries' : ActorMethod<[], Array<LabourEntry>>,
  'adminGetAllRainfallLogs' : ActorMethod<[], Array<RainfallLog>>,
  'adminGetAllRevenueEntries' : ActorMethod<[], Array<RevenueEntry>>,
  'adminGetAllUserPrincipals' : ActorMethod<[], Array<Principal>>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCropYield' : ActorMethod<[CropYield], bigint>,
  'createDailyLog' : ActorMethod<[DailyLog], bigint>,
  'createEstate' : ActorMethod<[Estate], bigint>,
  'createForecast' : ActorMethod<[Forecast], bigint>,
  'createLabourEntry' : ActorMethod<[LabourEntry], bigint>,
  'createRainfallLog' : ActorMethod<[RainfallLog], bigint>,
  'createRevenueEntry' : ActorMethod<[RevenueEntry], bigint>,
  'deleteCropYield' : ActorMethod<[bigint], undefined>,
  'deleteDailyLog' : ActorMethod<[bigint], undefined>,
  'deleteEstate' : ActorMethod<[bigint], undefined>,
  'deleteLabourEntry' : ActorMethod<[bigint], undefined>,
  'deleteRainfallLog' : ActorMethod<[bigint], undefined>,
  'deleteRevenueEntry' : ActorMethod<[bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCropYield' : ActorMethod<[bigint], CropYield>,
  'getDailyLog' : ActorMethod<[bigint], DailyLog>,
  'getEstate' : ActorMethod<[bigint], Estate>,
  'getForecast' : ActorMethod<[bigint], Forecast>,
  'getLabourEntry' : ActorMethod<[bigint], LabourEntry>,
  'getRainfallLog' : ActorMethod<[bigint], RainfallLog>,
  'getRevenueEntry' : ActorMethod<[bigint], RevenueEntry>,
  'getTotalExpensesForUser' : ActorMethod<[], number>,
  'getTotalRainfallForUser' : ActorMethod<[], number>,
  'getTotalRevenueForUser' : ActorMethod<[], number>,
  'getUserCropYields' : ActorMethod<[], Array<CropYield>>,
  'getUserDailyLogs' : ActorMethod<[], Array<DailyLog>>,
  'getUserEstates' : ActorMethod<[], Array<Estate>>,
  'getUserForecasts' : ActorMethod<[], Array<Forecast>>,
  'getUserLabourEntries' : ActorMethod<[], Array<LabourEntry>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserRainfallLogs' : ActorMethod<[], Array<RainfallLog>>,
  'getUserRevenueEntries' : ActorMethod<[], Array<RevenueEntry>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'claimAdminRole' : ActorMethod<[string], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];