/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CropYield = IDL.Record({
  'id' : IDL.Nat,
  'yieldKg' : IDL.Float64,
  'userId' : IDL.Principal,
  'year' : IDL.Nat,
  'cropName' : IDL.Text,
  'estateId' : IDL.Nat,
});
export const DailyLog = IDL.Record({
  'id' : IDL.Nat,
  'userId' : IDL.Principal,
  'date' : IDL.Text,
  'pesticideMl' : IDL.Float64,
  'laborHours' : IDL.Float64,
  'fertilizerKg' : IDL.Float64,
  'estateId' : IDL.Nat,
  'rainfallMM' : IDL.Float64,
});
export const Estate = IDL.Record({
  'id' : IDL.Nat,
  'estateCare' : IDL.Text,
  'userId' : IDL.Principal,
  'areaAcres' : IDL.Float64,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'location' : IDL.Text,
});
export const Forecast = IDL.Record({
  'id' : IDL.Nat,
  'userId' : IDL.Principal,
  'cropName' : IDL.Text,
  'forecastDate' : IDL.Text,
  'forecastNote' : IDL.Text,
  'estateId' : IDL.Nat,
});
export const LabourEntry = IDL.Record({
  'id' : IDL.Nat,
  'workType' : IDL.Text,
  'wagePerDay' : IDL.Float64,
  'userId' : IDL.Principal,
  'date' : IDL.Text,
  'numberOfDays' : IDL.Nat,
  'totalAmount' : IDL.Float64,
  'estateId' : IDL.Nat,
  'workerName' : IDL.Text,
});
export const RainfallLog = IDL.Record({
  'id' : IDL.Nat,
  'userId' : IDL.Principal,
  'date' : IDL.Text,
  'notes' : IDL.Text,
  'estateId' : IDL.Nat,
  'rainfallMM' : IDL.Float64,
});
export const RevenueEntry = IDL.Record({
  'id' : IDL.Nat,
  'userId' : IDL.Principal,
  'date' : IDL.Text,
  'description' : IDL.Text,
  'estateId' : IDL.Nat,
  'amount' : IDL.Float64,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCropYield' : IDL.Func([CropYield], [IDL.Nat], []),
  'createDailyLog' : IDL.Func([DailyLog], [IDL.Nat], []),
  'createEstate' : IDL.Func([Estate], [IDL.Nat], []),
  'createForecast' : IDL.Func([Forecast], [IDL.Nat], []),
  'createLabourEntry' : IDL.Func([LabourEntry], [IDL.Nat], []),
  'createRainfallLog' : IDL.Func([RainfallLog], [IDL.Nat], []),
  'createRevenueEntry' : IDL.Func([RevenueEntry], [IDL.Nat], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCropYield' : IDL.Func([IDL.Nat], [CropYield], ['query']),
  'getDailyLog' : IDL.Func([IDL.Nat], [DailyLog], ['query']),
  'getEstate' : IDL.Func([IDL.Nat], [Estate], ['query']),
  'getForecast' : IDL.Func([IDL.Nat], [Forecast], ['query']),
  'getLabourEntry' : IDL.Func([IDL.Nat], [LabourEntry], ['query']),
  'getRainfallLog' : IDL.Func([IDL.Nat], [RainfallLog], ['query']),
  'getRevenueEntry' : IDL.Func([IDL.Nat], [RevenueEntry], ['query']),
  'getTotalExpensesForUser' : IDL.Func([], [IDL.Float64], ['query']),
  'getTotalRainfallForUser' : IDL.Func([], [IDL.Float64], ['query']),
  'getTotalRevenueForUser' : IDL.Func([], [IDL.Float64], ['query']),
  'getUserCropYields' : IDL.Func([], [IDL.Vec(CropYield)], ['query']),
  'getUserDailyLogs' : IDL.Func([], [IDL.Vec(DailyLog)], ['query']),
  'getUserEstates' : IDL.Func([], [IDL.Vec(Estate)], ['query']),
  'getUserForecasts' : IDL.Func([], [IDL.Vec(Forecast)], ['query']),
  'getUserLabourEntries' : IDL.Func([], [IDL.Vec(LabourEntry)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserRainfallLogs' : IDL.Func([], [IDL.Vec(RainfallLog)], ['query']),
  'getUserRevenueEntries' : IDL.Func([], [IDL.Vec(RevenueEntry)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CropYield = IDL.Record({
    'id' : IDL.Nat,
    'yieldKg' : IDL.Float64,
    'userId' : IDL.Principal,
    'year' : IDL.Nat,
    'cropName' : IDL.Text,
    'estateId' : IDL.Nat,
  });
  const DailyLog = IDL.Record({
    'id' : IDL.Nat,
    'userId' : IDL.Principal,
    'date' : IDL.Text,
    'pesticideMl' : IDL.Float64,
    'laborHours' : IDL.Float64,
    'fertilizerKg' : IDL.Float64,
    'estateId' : IDL.Nat,
    'rainfallMM' : IDL.Float64,
  });
  const Estate = IDL.Record({
    'id' : IDL.Nat,
    'estateCare' : IDL.Text,
    'userId' : IDL.Principal,
    'areaAcres' : IDL.Float64,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'location' : IDL.Text,
  });
  const Forecast = IDL.Record({
    'id' : IDL.Nat,
    'userId' : IDL.Principal,
    'cropName' : IDL.Text,
    'forecastDate' : IDL.Text,
    'forecastNote' : IDL.Text,
    'estateId' : IDL.Nat,
  });
  const LabourEntry = IDL.Record({
    'id' : IDL.Nat,
    'workType' : IDL.Text,
    'wagePerDay' : IDL.Float64,
    'userId' : IDL.Principal,
    'date' : IDL.Text,
    'numberOfDays' : IDL.Nat,
    'totalAmount' : IDL.Float64,
    'estateId' : IDL.Nat,
    'workerName' : IDL.Text,
  });
  const RainfallLog = IDL.Record({
    'id' : IDL.Nat,
    'userId' : IDL.Principal,
    'date' : IDL.Text,
    'notes' : IDL.Text,
    'estateId' : IDL.Nat,
    'rainfallMM' : IDL.Float64,
  });
  const RevenueEntry = IDL.Record({
    'id' : IDL.Nat,
    'userId' : IDL.Principal,
    'date' : IDL.Text,
    'description' : IDL.Text,
    'estateId' : IDL.Nat,
    'amount' : IDL.Float64,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCropYield' : IDL.Func([CropYield], [IDL.Nat], []),
    'createDailyLog' : IDL.Func([DailyLog], [IDL.Nat], []),
    'createEstate' : IDL.Func([Estate], [IDL.Nat], []),
    'createForecast' : IDL.Func([Forecast], [IDL.Nat], []),
    'createLabourEntry' : IDL.Func([LabourEntry], [IDL.Nat], []),
    'createRainfallLog' : IDL.Func([RainfallLog], [IDL.Nat], []),
    'createRevenueEntry' : IDL.Func([RevenueEntry], [IDL.Nat], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCropYield' : IDL.Func([IDL.Nat], [CropYield], ['query']),
    'getDailyLog' : IDL.Func([IDL.Nat], [DailyLog], ['query']),
    'getEstate' : IDL.Func([IDL.Nat], [Estate], ['query']),
    'getForecast' : IDL.Func([IDL.Nat], [Forecast], ['query']),
    'getLabourEntry' : IDL.Func([IDL.Nat], [LabourEntry], ['query']),
    'getRainfallLog' : IDL.Func([IDL.Nat], [RainfallLog], ['query']),
    'getRevenueEntry' : IDL.Func([IDL.Nat], [RevenueEntry], ['query']),
    'getTotalExpensesForUser' : IDL.Func([], [IDL.Float64], ['query']),
    'getTotalRainfallForUser' : IDL.Func([], [IDL.Float64], ['query']),
    'getTotalRevenueForUser' : IDL.Func([], [IDL.Float64], ['query']),
    'getUserCropYields' : IDL.Func([], [IDL.Vec(CropYield)], ['query']),
    'getUserDailyLogs' : IDL.Func([], [IDL.Vec(DailyLog)], ['query']),
    'getUserEstates' : IDL.Func([], [IDL.Vec(Estate)], ['query']),
    'getUserForecasts' : IDL.Func([], [IDL.Vec(Forecast)], ['query']),
    'getUserLabourEntries' : IDL.Func([], [IDL.Vec(LabourEntry)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserRainfallLogs' : IDL.Func([], [IDL.Vec(RainfallLog)], ['query']),
    'getUserRevenueEntries' : IDL.Func([], [IDL.Vec(RevenueEntry)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };