/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Estate {
    id: bigint;
    estateCare: string;
    userId: Principal;
    areaAcres: number;
    name: string;
    createdAt: bigint;
    location: string;
}
export interface RainfallLog {
    id: bigint;
    userId: Principal;
    date: string;
    notes: string;
    estateId: bigint;
    rainfallMM: number;
}
export interface LabourEntry {
    id: bigint;
    workType: string;
    wagePerDay: number;
    userId: Principal;
    date: string;
    numberOfDays: bigint;
    totalAmount: number;
    estateId: bigint;
    workerName: string;
}
export interface Forecast {
    id: bigint;
    userId: Principal;
    cropName: string;
    forecastDate: string;
    forecastNote: string;
    estateId: bigint;
}
export interface RevenueEntry {
    id: bigint;
    userId: Principal;
    date: string;
    description: string;
    estateId: bigint;
    amount: number;
}
export interface DailyLog {
    id: bigint;
    userId: Principal;
    date: string;
    pesticideMl: number;
    laborHours: number;
    fertilizerKg: number;
    estateId: bigint;
    rainfallMM: number;
}
export interface CropYield {
    id: bigint;
    yieldKg: number;
    userId: Principal;
    year: bigint;
    cropName: string;
    estateId: bigint;
}
export interface UserProfile {
    name: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    adminDeleteCropYield(yieldId: bigint): Promise<void>;
    adminDeleteDailyLog(logId: bigint): Promise<void>;
    adminDeleteEstate(estateId: bigint): Promise<void>;
    adminDeleteLabourEntry(entryId: bigint): Promise<void>;
    adminDeleteRainfallLog(logId: bigint): Promise<void>;
    adminDeleteRevenueEntry(entryId: bigint): Promise<void>;
    adminGetAllCropYields(): Promise<Array<CropYield>>;
    adminGetAllDailyLogs(): Promise<Array<DailyLog>>;
    adminGetAllEstates(): Promise<Array<Estate>>;
    adminGetAllLabourEntries(): Promise<Array<LabourEntry>>;
    adminGetAllRainfallLogs(): Promise<Array<RainfallLog>>;
    adminGetAllRevenueEntries(): Promise<Array<RevenueEntry>>;
    adminGetAllUserPrincipals(): Promise<Array<Principal>>;
    ensureUserInRegistry(): Promise<void>;
    adminGetAllUsers(): Promise<Array<{principalId: Principal; name: string; role: string; createdAt: bigint}>>;
    adminDeleteUserFromRegistry(user: Principal): Promise<void>;
    adminUpdateUserRole(user: Principal, role: UserRole): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createCropYield(yield: CropYield): Promise<bigint>;
    createDailyLog(log: DailyLog): Promise<bigint>;
    createEstate(estate: Estate): Promise<bigint>;
    createForecast(forecast: Forecast): Promise<bigint>;
    createLabourEntry(entry: LabourEntry): Promise<bigint>;
    createRainfallLog(log: RainfallLog): Promise<bigint>;
    createRevenueEntry(entry: RevenueEntry): Promise<bigint>;
    deleteCropYield(yieldId: bigint): Promise<void>;
    deleteDailyLog(logId: bigint): Promise<void>;
    deleteEstate(estateId: bigint): Promise<void>;
    deleteLabourEntry(entryId: bigint): Promise<void>;
    deleteRainfallLog(logId: bigint): Promise<void>;
    deleteRevenueEntry(entryId: bigint): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCropYield(yieldId: bigint): Promise<CropYield>;
    getDailyLog(logId: bigint): Promise<DailyLog>;
    getEstate(estateId: bigint): Promise<Estate>;
    getForecast(forecastId: bigint): Promise<Forecast>;
    getLabourEntry(entryId: bigint): Promise<LabourEntry>;
    getRainfallLog(logId: bigint): Promise<RainfallLog>;
    getRevenueEntry(entryId: bigint): Promise<RevenueEntry>;
    getTotalExpensesForUser(): Promise<number>;
    getTotalRainfallForUser(): Promise<number>;
    getTotalRevenueForUser(): Promise<number>;
    getUserCropYields(): Promise<Array<CropYield>>;
    getUserDailyLogs(): Promise<Array<DailyLog>>;
    getUserEstates(): Promise<Array<Estate>>;
    getUserForecasts(): Promise<Array<Forecast>>;
    getUserLabourEntries(): Promise<Array<LabourEntry>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUserRainfallLogs(): Promise<Array<RainfallLog>>;
    getUserRevenueEntries(): Promise<Array<RevenueEntry>>;
    isCallerAdmin(): Promise<boolean>;
    claimAdminRole(secret: string): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
}
import type { UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async adminDeleteCropYield(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminDeleteCropYield(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminDeleteCropYield(arg0);
            return result;
        }
    }
    async adminDeleteDailyLog(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminDeleteDailyLog(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminDeleteDailyLog(arg0);
            return result;
        }
    }
    async adminDeleteEstate(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminDeleteEstate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminDeleteEstate(arg0);
            return result;
        }
    }
    async adminDeleteLabourEntry(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminDeleteLabourEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminDeleteLabourEntry(arg0);
            return result;
        }
    }
    async adminDeleteRainfallLog(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminDeleteRainfallLog(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminDeleteRainfallLog(arg0);
            return result;
        }
    }
    async adminDeleteRevenueEntry(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminDeleteRevenueEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminDeleteRevenueEntry(arg0);
            return result;
        }
    }
    async adminGetAllCropYields(): Promise<Array<CropYield>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetAllCropYields();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetAllCropYields();
            return result;
        }
    }
    async adminGetAllDailyLogs(): Promise<Array<DailyLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetAllDailyLogs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetAllDailyLogs();
            return result;
        }
    }
    async adminGetAllEstates(): Promise<Array<Estate>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetAllEstates();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetAllEstates();
            return result;
        }
    }
    async adminGetAllLabourEntries(): Promise<Array<LabourEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetAllLabourEntries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetAllLabourEntries();
            return result;
        }
    }
    async adminGetAllRainfallLogs(): Promise<Array<RainfallLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetAllRainfallLogs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetAllRainfallLogs();
            return result;
        }
    }
    async adminGetAllRevenueEntries(): Promise<Array<RevenueEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetAllRevenueEntries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetAllRevenueEntries();
            return result;
        }
    }
    async adminGetAllUserPrincipals(): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetAllUserPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetAllUserPrincipals();
            return result;
        }
    }
    async ensureUserInRegistry(): Promise<void> {
        if (this.processError) {
            try {
                await this.actor.ensureUserInRegistry();
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            await this.actor.ensureUserInRegistry();
        }
    }
    async adminGetAllUsers(): Promise<Array<{principalId: Principal; name: string; role: string; createdAt: bigint}>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetAllUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetAllUsers();
            return result;
        }
    }
    async adminDeleteUserFromRegistry(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                await this.actor.adminDeleteUserFromRegistry(arg0);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            await this.actor.adminDeleteUserFromRegistry(arg0);
        }
    }
    async adminUpdateUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                await this.actor.adminUpdateUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            await this.actor.adminUpdateUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createCropYield(arg0: CropYield): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createCropYield(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCropYield(arg0);
            return result;
        }
    }
    async createDailyLog(arg0: DailyLog): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createDailyLog(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDailyLog(arg0);
            return result;
        }
    }
    async createEstate(arg0: Estate): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createEstate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createEstate(arg0);
            return result;
        }
    }
    async createForecast(arg0: Forecast): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createForecast(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createForecast(arg0);
            return result;
        }
    }
    async createLabourEntry(arg0: LabourEntry): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createLabourEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createLabourEntry(arg0);
            return result;
        }
    }
    async createRainfallLog(arg0: RainfallLog): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createRainfallLog(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createRainfallLog(arg0);
            return result;
        }
    }
    async createRevenueEntry(arg0: RevenueEntry): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createRevenueEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createRevenueEntry(arg0);
            return result;
        }
    }
    async deleteCropYield(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCropYield(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCropYield(arg0);
            return result;
        }
    }
    async deleteDailyLog(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDailyLog(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDailyLog(arg0);
            return result;
        }
    }
    async deleteEstate(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteEstate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteEstate(arg0);
            return result;
        }
    }
    async deleteLabourEntry(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteLabourEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteLabourEntry(arg0);
            return result;
        }
    }
    async deleteRainfallLog(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteRainfallLog(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteRainfallLog(arg0);
            return result;
        }
    }
    async deleteRevenueEntry(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteRevenueEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteRevenueEntry(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCropYield(arg0: bigint): Promise<CropYield> {
        if (this.processError) {
            try {
                const result = await this.actor.getCropYield(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCropYield(arg0);
            return result;
        }
    }
    async getDailyLog(arg0: bigint): Promise<DailyLog> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailyLog(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailyLog(arg0);
            return result;
        }
    }
    async getEstate(arg0: bigint): Promise<Estate> {
        if (this.processError) {
            try {
                const result = await this.actor.getEstate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEstate(arg0);
            return result;
        }
    }
    async getForecast(arg0: bigint): Promise<Forecast> {
        if (this.processError) {
            try {
                const result = await this.actor.getForecast(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getForecast(arg0);
            return result;
        }
    }
    async getLabourEntry(arg0: bigint): Promise<LabourEntry> {
        if (this.processError) {
            try {
                const result = await this.actor.getLabourEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLabourEntry(arg0);
            return result;
        }
    }
    async getRainfallLog(arg0: bigint): Promise<RainfallLog> {
        if (this.processError) {
            try {
                const result = await this.actor.getRainfallLog(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRainfallLog(arg0);
            return result;
        }
    }
    async getRevenueEntry(arg0: bigint): Promise<RevenueEntry> {
        if (this.processError) {
            try {
                const result = await this.actor.getRevenueEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRevenueEntry(arg0);
            return result;
        }
    }
    async getTotalExpensesForUser(): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalExpensesForUser();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalExpensesForUser();
            return result;
        }
    }
    async getTotalRainfallForUser(): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalRainfallForUser();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalRainfallForUser();
            return result;
        }
    }
    async getTotalRevenueForUser(): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalRevenueForUser();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalRevenueForUser();
            return result;
        }
    }
    async getUserCropYields(): Promise<Array<CropYield>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserCropYields();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserCropYields();
            return result;
        }
    }
    async getUserDailyLogs(): Promise<Array<DailyLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserDailyLogs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserDailyLogs();
            return result;
        }
    }
    async getUserEstates(): Promise<Array<Estate>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserEstates();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserEstates();
            return result;
        }
    }
    async getUserForecasts(): Promise<Array<Forecast>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserForecasts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserForecasts();
            return result;
        }
    }
    async getUserLabourEntries(): Promise<Array<LabourEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserLabourEntries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserLabourEntries();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserRainfallLogs(): Promise<Array<RainfallLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserRainfallLogs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserRainfallLogs();
            return result;
        }
    }
    async getUserRevenueEntries(): Promise<Array<RevenueEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserRevenueEntries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserRevenueEntries();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async claimAdminRole(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.claimAdminRole(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.claimAdminRole(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
}
function from_candid_UserRole_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
